### ISSUE TITLE
wrong directory makeipsw.sh#L67 ?

### ISSUE THREAD

**Issue by fenfenS** [verygenericname/TV4K_IPSW_Script#1]
https://github.com/verygenericname/TV4K_IPSW_Script/blob/5ad1c1a142ceff82282e6b226ba4191af3004a7f/makeipsw.sh#L67
and the next lines , should be ../work/ota instead of ../ota ?

**Comment by verygenericname** [comment]
It's already in the work folder

**Comment by fenfenS** [comment]
Sorry for my mistake, actually I shouldn't use relative addresses here, an absolute address is required as a parameter.
